export const FLOW_CONFIG = {
  MAX_EVENTS_PER_BUNDLE: 50,
  MAX_RECENT_BLOCKS_CTX: 10,
  PENDING_WARN_THRESHOLD: 3,
  BUNDLE_TTL_DAYS: 7,
  DELTA_LOG_ROTATE_MB: 10,
  DELTA_STALE_COUNT: 100,
  CUE_CARD_SOFT_KB: 4,
  CUE_CARD_HARD_KB: 6,
  STDOUT_INJECT_BUDGET_KB: 1.5,
  FALLBACK_CARD_BUDGET_KB: 1,
} as const;
